/* Explication du fonctionnement :
J'ai plusieurs section et paragraphes / titre avec des ids qui ont une fonction chacun (par exemple le nom du champion / Son histoire ..)
Lorsque l'on clique sur un champion en particulier, je remplace le contenue de ces textes par celui approprié au champion.

Le code peut paraitre très long ou complexe, mais la plupart de celui ci est tout simplement du texte tel que l'histoire des champions étant souvent longue.*/

let wallpaper = document.getElementById('wallpaper');
var LeTitre = document.getElementById("LeTitre")
var LeReste = document.getElementById("LeReste")
var Limage = document.getElementById("Limage");
var LaClasse = document.getElementById("LaClasse");
var descplus = document.getElementById("descplus");
var LogoClasse = document.getElementById("LogoClasse");
var Lerreur = document.getElementById("erreur");
var audio = document.getElementById("audio");
var divvideo = document.getElementById("divvideo");
var video = document.getElementById("video");
var sousvideo = document.getElementById("avertissement");
var desc1 = document.getElementById("titredesc");
var desc2 = document.getElementById("videodesc");
var defpop1 = document.getElementById("defpop1");
var defpop2 = document.getElementById("defpop2");
var sepdesc = document.getElementById("sepdesc");

var flank = "Classe du champion : <span>Flank</span>";
var dmg = "Classe du champion : <span>Dégât</span>";
var tank = "Classe du champion : <span>Tank</span>";
var healer = "Classe du champion : <span>Healer</span>";

window.addEventListener('scroll', function () {
    let value = window.scrollY;
    wallpaper.style.top = value * 0.5 + 'px';
})

var getvalue = document.getElementsByName('Champion')[0];

/* Code que j'execute base, pour choisir un champion aléatoire parmis tous ce qui existe et l'afficher*/

const champion = ["Octavia", "Yagorath", "Vatu", "Azaan", "Rei", "Androxus", "Ash", "Atlas", "Barik", "BombKing", "Buck", "Cassie", "Corvus", "Dredge", "Drogoz", "Evie", "Fernando", "Furia", "Grohk", "Grover", "Imani", "Inara", "Io", "Jenos", "Khan", "Kinessa", "Koga", "Lex", "Lian", "Maeve", "Makoa", "Mal'Damba", "Moji", "Pip", "Raum", "Ruckus", "Seris", "Sha Lin", "Skye", "Strix", "Talus", "Terminus", "Tiberius", "Torvald", "Tyra", "Viktor", "Vivian", "Vora", "Willo", "Ying", "Zhin"];
getvalue.value = champion[Math.floor(Math.random() * champion.length)];
cliquebtn();

function listechampbtn(champ) {
    getvalue.value = champ;
    cliquebtn();
}

function deflore() {
    if (defpop1.style.display == "none") {
        defpop1.style.display = "block";
    } else {
        defpop1.style.display = "none";
    }
}

function deflore2() {
    if (defpop2.style.display == "none") {
        defpop2.style.display = "block";
    } else {
        defpop2.style.display = "none";
    }
}

function montrevideo() {
    video.style.display = "block";
    divvideo.style.display = "block";
    sousvideo.style.display = "block";
    Lerreur.innerHTML = "Champion Trouvé !";
    Lerreur.style.color = "#B5E655";
    desc1.style.display = "block";
    desc2.style.display = "block";
    sepdesc.style.display = "block";
    removedeflore();
    removedeflore2();
    audio.volume = 0.5;
}

function errouge() {
    Lerreur.style.color = "rgb(250, 83, 83)";
}

function cliquebtn() {
    Lerreur.innerHTML = "";
    switch (getvalue.value) {
        case "Androxus": LeTitre.innerHTML = "Androxus";
            LeReste.innerHTML = "Le Pourfendeur Des Dieux";
            Limage.src = "banniere_perso/androxus.png";
            LaClasse.innerHTML = flank + "<br><i>(2100 PV)</i>";
            LogoClasse.src = "img/flank.png";
            descplus.innerHTML = "Ancien juge du Tribunal Extérieur, Androxus était un homme puissant, craint et respecté autant de ses ennemis que de ses alliés. En tant que juge, il était chargé de rendre justice armé d'un revolver en la compagnie de son coéquipier et ami Lex. Cependant, lors de la destruction de la ville de Seris, il fut vaincu puis maudit par l'oracle mais obtint les capacités de planer, absorber puis renvoyer les attaques et charger son revolver maudit d'énergie magique pour ensuite la projeter sous la forme de balles explosives. Depuis ce jour, le juge déchu recherche activement des âmes puissantes pour échapper à sa malédiction et peut-être, un jour, trouver la paix.";
            audio.src = "voiceline/Androxus.ogg";
            video.src = "https://www.youtube.com/embed/qjGyIrm9qtQ";
            montrevideo();
            break;
        case "Ash": LeTitre.innerHTML = "Ash";
            LeReste.innerHTML = "La Machine De Guerre";
            Limage.src = "banniere_perso/ash.png";
            LaClasse.innerHTML = tank + "<br><i>(4500 PV)</i>";
            LogoClasse.src = "img/tank.png";
            descplus.innerHTML = "Surnommée 'La Machine de Guerre' par ses alliés comme ses adversaires, Ash s'est illustrée au front autant par l'utilisation de son armure et de son canon explosif que par ses méthodes brutales, extrêmes et expéditives. Elle se fit notamment un nom lors de l'avènement de la Résistance où elle tua Terminus d'un seul tir de canon dans la poitrine, sous les yeux horrifiés d'Inara, des Paladins et des habitants de Soufflecroix. ";
            audio.src = "voiceline/Ash.ogg";
            video.src = "https://www.youtube.com/embed/BDYGoklCgP0";
            montrevideo();
            break;
        case "Atlas": LeTitre.innerHTML = "Atlas";
            LeReste.innerHTML = "L'Intemporel";
            Limage.src = "banniere_perso/atlas.png";
            LaClasse.innerHTML = tank + "<br><i>(3500 PV)</i>";
            LogoClasse.src = "img/tank.png";
            descplus.innerHTML = "Fils du juge légendaire Lex, Atlas vient d'un futur où les ténèbres des Abysses ont tout englouti, éliminant quiconque se dressait sur leur chemin. Luttant constamment pour sa survie, il ne trouve du réconfort que dans les contes évoquant le Royaume et sa gloire d'antan, bien avant l'issue tragique de la bataille finale entre la lumière et les ténèbres. Découvrant ce qui permit aux Abysses d'engloutir le monde, Atlas étudia la magie des cristaux et parvint à maîtriser le temps lui-même. Fort de ses connaissances et de ses nouveaux pouvoirs, il prit la décision de retourner dans le passé pour sauver le Royaume et changer le cours de l'Histoire.";
            audio.src = "voiceline/Atlas.ogg";
            video.src = "https://www.youtube.com/embed/ZOdlw9XvMKY";
            montrevideo();
            break;
        case "Azaan": LeTitre.innerHTML = "Azaan";
            LeReste.innerHTML = "L'Eternel";
            Limage.src = "banniere_perso/azaan.png";
            LaClasse.innerHTML = tank + "<br><i>(4500 PV)</i>";
            LogoClasse.src = "img/tank.png";
            descplus.innerHTML = "Une fois le roi d’un royaume longtemps oublié, l’Éternel a existé pour voir la fin d’innombrables règnes. Forgé dans le creuset des flammes du Pyre comme l’incarnation de tout ce qui persiste, Azaan est chargé de maintenir l’existence d’un Royaume tenu à l’abri de l’influence abyssale.<br><br>Peu de vivants ont jamais eu de raison de s’engager avec l’un des plus anciens des Seigneurs de Pyre, mais ceux qui ont su que ses flammes purificatrices ne se soucient pas d’ami ou d’ennemi, seulement pour l’éradication complète de l’Abysse. Les événements dans le Royaume ont bouleversé l’équilibre, conduisant à l’influence de l’Abîme qui se rapproche de plus en plus, et ainsi l’Éternel descend d’en haut pour délivrer un dernier avertissement au Royaume : traitez avec l’Abîme, ou faites-le traiter, par tous les moyens jugés nécessaires.";
            audio.src = "voiceline/Azaan.ogg";
            video.src = "https://www.youtube.com/embed/H69NifMn4rA";
            montrevideo();
            break;
        case "Barik": LeTitre.innerHTML = "Barik";
            LeReste.innerHTML = "Le Maître Mécanicien";
            Limage.src = "banniere_perso/barik.png";
            LaClasse.innerHTML = tank + "<br><i>(3400 PV)</i>";
            LogoClasse.src = "img/tank.png";
            descplus.innerHTML = "Ingénieur nain reconnu dans tout le Royaume, Barik se démarqua grâce à ses inventions alimentées par les cristaux magiques. Allant d'exosquelettes pour mineurs à l'épée de guerre de Valera en passant par les ailes mécaniques dérobées par Drogoz, Barik fut pourtant contre l'usage des cristaux à des fins militaires et, comprenant que le Magistrat lui préférait Vivian, quitta Engrenage pour rejoindre la Résistance et réduire les plans machiavéliques de sa rivale à néant.";
            audio.src = "voiceline/Barik.ogg";
            video.src = "https://www.youtube.com/embed/XCFxif1c52g";
            montrevideo();
            break;
        case "BombKing": LeTitre.innerHTML = "Bomb King";
            LeReste.innerHTML = "Sa Majesté";
            Limage.src = "banniere_perso/bombking.png";
            LaClasse.innerHTML = dmg + "<br><i>(2200 PV)</i>";
            LogoClasse.src = "img/dmg.png";
            descplus.innerHTML = "Véritable bombe vivante, Bomb King est un être ayant un caractère très enflammé et un sens de l'humour particulièrement explosif. Convaincu de gouverner le Royaume malgré sa nature et sa puissance destructrice, il passe son temps à se promener sans vraiment réaliser le danger qu'il représente pour les habitants. Bien que créé par un puissant sorcier, la volonté et l'intelligence de Bomb King lui ont permis de recréer des bombes vivantes lui permettant par exemple d'étourdir les ennemis ou de voler sur de courtes distances.";
            audio.src = "voiceline/BombKing.ogg";
            video.src = "https://www.youtube.com/embed/GCJSW6Vqyk4";
            montrevideo();
            break;
        case "Buck": LeTitre.innerHTML = "Buck";
            LeReste.innerHTML = "L'Inflexible";
            Limage.src = "banniere_perso/buck.png";
            LaClasse.innerHTML = flank + "<br><i>(2300 PV)</i>";
            LogoClasse.src = "img/flank.png";
            descplus.innerHTML = "Tour à tour élève de Jenos en tant que moine, bandit puis soldat, Buck fut également le plus proche garde du corps du Magistère Karne. Après le fiasco des Sentinelles, Buck prit la décision de quitter Engrenage et retourna à la forteresse de Soufflecroix afin de mettre ses poings et son fusil à canon scié au service des habitants et des Paladins.";
            audio.src = "voiceline/Buck.ogg";
            video.src = "https://www.youtube.com/embed/QXFSjpXsrpQ";
            montrevideo();
            break;
        case "Cassie": LeTitre.innerHTML = "Cassie";
            LeReste.innerHTML = "La Fille Du Chasseur";
            Limage.src = "banniere_perso/cassie.png";
            LaClasse.innerHTML = dmg + "<br><i>(2200 PV)</i>";
            LogoClasse.src = "img/dmg.png";
            descplus.innerHTML = "Jeune chasseresse armée d'une arbalète magique et accompagnée par son fidèle oiseau, Cassie est une jeune fille enjouée et téméraire qui cache cependant un lourd secret : elle réussit à échanger sa liberté et le droit de quitter son village natal au prix de la survie de celui-ci. Honteuse et rongée par la culpabilité, elle décida de mettre ses compétences et ses flèches magiques au service des Paladins.";
            audio.src = "voiceline/Cassie.ogg";
            video.src = "https://www.youtube.com/embed/gYLIuhaOuog";
            montrevideo();
            break;
        case "Corvus": LeTitre.innerHTML = "Corvus";
            LeReste.innerHTML = "Lame Du Magistrat";
            Limage.src = "banniere_perso/corvus.png";
            LaClasse.innerHTML = healer + "<br><i>(2200 PV)</i>";
            LogoClasse.src = "img/healer.png";
            descplus.innerHTML = "Les décisions les plus difficiles mettent à l’épreuve même les volontés les plus fortes, mais sa volonté n’a jamais faibli, même face à des probabilités apparemment insurmontables. C’est Corvus, la lame du magistrat. Il est le fils de Karne, le puissant chef du Magistrat, mais c’est par son propre mérite qu’il a gagné la loyauté absolue de ses hommes et instillé la peur dans ses ennemis.<br><br>Leader charismatique et brillant tacticien, Corvus ne reculera devant rien pour voir ses objectifs réalisés : une paix pour dépasser celle de l’Âge d’Or, sous le règne du Magistrat. Avec l’énergie quasi illimitée de l’Abîme, tendu à sa volonté de fer, et ces soldats encore fidèles à sa vision de la paix, il fait ce dont aucun autre n’est capable. Par sa propre force, la Résistance tombera, et la paix sera forgée pour les citoyens du Royaume, avec ou sans leur coopération. ";
            audio.src = "voiceline/Corvus.ogg";
            video.src = "https://www.youtube.com/embed/XucbBXE8usU";
            montrevideo();
            break;
        case "Dredge": LeTitre.innerHTML = "Dredge";
            LeReste.innerHTML = "Amiral Abyssal";
            Limage.src = "banniere_perso/dredge.png";
            LaClasse.innerHTML = dmg + "<br><i>(2200 PV)</i>";
            LogoClasse.src = "img/dmg.png";
            descplus.innerHTML = "Ancien pirate revenu d'entre les morts grâce aux Abysses, Dredge possède un mortier maudit tirant des bombes infligeant à la fois des dégâts directs et de zone, permettant de mettre la pression sur l'ennemi. Doté de nouveaux pouvoirs lors de sa résurrection comme la création d'un harpon spectral ou de portails dimensionnels, Dredge va chercher à se venger des Paladins et récupérer son trésor, quitte à déchaîner les terrifiantes tentacules du Kraken.";
            audio.src = "voiceline/Dredge.ogg";
            video.src = "https://www.youtube.com/embed/JKJmoj7ppw8";
            montrevideo();
            break;
        case "Drogoz": LeTitre.innerHTML = "Drogoz";
            LeReste.innerHTML = "Le Dévoreur";
            Limage.src = "banniere_perso/drogoz.png";
            LaClasse.innerHTML = dmg + "<br><i>(2200 PV)</i>";
            LogoClasse.src = "img/dmg.png";
            descplus.innerHTML = "Contrairement aux autres dragons, Drogoz est né sans ailes, l'empêchant par conséquent de voler, gagner le respect de son peuple et s'émanciper de sa condition de serviteur d'un grand dragon. Cependant, le vouivrin réussit à dérober dans l'atelier de Barik un exosquelette équipé d'ailes mécaniques et d'un lance-roquettes alimentés par un cristal magique. Depuis ce jour, Drogoz déchaîne ses roquettes et son souffle de feu sur tout le Royaume dans le but de lever une armée et ainsi affronter les grands dragons.";
            audio.src = "voiceline/Drogoz.ogg";
            video.src = "https://www.youtube.com/embed/6dpqtFF-Xa0";
            montrevideo();
            break;
        case "Evie": LeTitre.innerHTML = "Evie";
            LeReste.innerHTML = "La Sorcière De L'Hiver";
            Limage.src = "banniere_perso/evie.png";
            LaClasse.innerHTML = flank + "<br><i>(1800 PV)</i>";
            LogoClasse.src = "img/flank.png";
            descplus.innerHTML = "Evie n'était au départ qu'une simple apprentie sorcière qui, grâce à une ruse efficace, réussit à emprisonner un esprit de givre auquel elle vola les pouvoirs. Etant devenue très puissante, elle fut chassée de son village qui craignait de subir la colère de l'esprit et que la magie n'échappe au contrôle de la jeune fille qui, malgré tout, trouva une certaine compensation dans le conflit entre le Magistrat et les Paladins.";
            audio.src = "voiceline/Evie.ogg";
            video.src = "https://www.youtube.com/embed/oXDcLUEdkmk";
            montrevideo();
            break;
        case "Fernando": LeTitre.innerHTML = "Fernando";
            LeReste.innerHTML = "Le Chevalier Autoproclamé";
            Limage.src = "banniere_perso/fernando.png";
            LaClasse.innerHTML = tank + "<br><i>(4600 PV)</i>";
            LogoClasse.src = "img/tank.png";
            descplus.innerHTML = "Avant de devenir chevalier, Fernando était un simple écuyer, déterminé et rêveur. A la mort prématurée de son maître, le jeune homme, souhaitant faire perdurer sa mémoire et être reconnu par la tête du Royaume, s'appropria son armure, son lance-flammes et s'adouba lui-même. Dès lors, Fernando partit offrir son aide à quiconque en aurait besoin jusqu'au jour où, ses exploits faisant le tour du Royaume, le Magistère l'appela à rejoindre son armée, usant du désir de reconnaissance de ce dernier.";
            audio.src = "voiceline/Fernando.ogg";
            video.src = "https://www.youtube.com/embed/xnOK-TNKNmw";
            montrevideo();
            break;
        case "Furia": LeTitre.innerHTML = "Furia";
            LeReste.innerHTML = "L'Ange Vengeur";
            Limage.src = "banniere_perso/furia.png";
            LaClasse.innerHTML = healer + "<br><i>(2200 PV)</i>";
            LogoClasse.src = "img/healer.png";
            descplus.innerHTML = "Furia, l'ange vengeur, est née le jour où Sarah, jeune femme vivant à Seris, implora le Bûcher Éternel de la sauver des Abysses et de venger sa sœur offerte en sacrifice. Malgré la destruction de sa ville natale, elle devint la flamme purificatrice et, armée de l’Épée Éternelle, s'élança dans une violente bataille contre les Abysses, dont l'oracle possédant désormais le corps de sa sœur.";
            audio.src = "voiceline/Furia.ogg";
            video.src = "https://www.youtube.com/embed/Ui9ix2gSawA";
            montrevideo();
            break;
        case "Grohk": LeTitre.innerHTML = "Grohk";
            LeReste.innerHTML = "L'Orc De Foudre";
            Limage.src = "banniere_perso/grohk.png";
            LaClasse.innerHTML = healer + "<br><i>(2200 PV)</i>";
            LogoClasse.src = "img/healer.png";
            descplus.innerHTML = "Être frappé par la foudre une fois est généralement plus que suffisant pour tuer quelqu'un, mais après des dizaines de frappes, Grohk était toujours debout. Comprenant qu'il possédait le pouvoir de contrôler la foudre, l'orc utilisa ses nouveaux pouvoirs pour défendre sa tribu contre une attaque de gobelins et en devint par la suite le chef. Cependant, quand la guerre civile éclata et se répandit jusqu'à la Rivière Rouge, Grohk prit les armes au nom de sa tribu. ";
            audio.src = "voiceline/Grohk.ogg";
            video.src = "https://www.youtube.com/embed/k-FjLFmSzZA";
            montrevideo();
            break;
        case "Grover": LeTitre.innerHTML = "Grover";
            LeReste.innerHTML = "La Nature Sauvage";
            Limage.src = "banniere_perso/grover.png";
            LaClasse.innerHTML = healer + "<br><i>(2300 PV)</i>";
            LogoClasse.src = "img/healer.png";
            descplus.innerHTML = "Grover, l'incarnation de la forêt, est un arbre en colère qui, après un sommeil de plusieurs décennies, s'est éveillé pour faire face aux ravages de la société humanoïde, de l'industrialisation, et de la guerre sur la nature. Armé de sa hache en pierre, Grover compte bien détruire tout ce qui menace de près ou de loin la nature dont il est le plus grand défenseur.";
            audio.src = "voiceline/Grover.ogg";
            video.src = "https://www.youtube.com/embed/_zYwRRCytG0";
            montrevideo();
            break;
        case "Imani": LeTitre.innerHTML = "Imani";
            LeReste.innerHTML = "La Dernière Protectrice";
            Limage.src = "banniere_perso/imani.png";
            LaClasse.innerHTML = dmg + "<br><i>(2200 PV)</i>";
            LogoClasse.src = "img/dmg.png";
            descplus.innerHTML = "Imani est la dernière Protectrice, ce qui fait d'elle la gardienne des gantelets draconiens et la seule personne capable d'invoquer et contrôler les dragons. Ses gantelets, récupérés dans la chambre forte de Dredge après qu'il les a dérobés aux Paladins, lui permettent également d'utiliser tour à tour des sorts de feu et de glace.";
            audio.src = "voiceline/Imani.ogg";
            video.src = "https://www.youtube.com/embed/iga0YSUITjE";
            montrevideo();
            break;
        case "Inara": LeTitre.innerHTML = "Inara";
            LeReste.innerHTML = "La Gardienne De Pierre";
            Limage.src = "banniere_perso/inara.png";
            LaClasse.innerHTML = tank + "<br><i>(4700 PV)</i>";
            LogoClasse.src = "img/tank.png";
            descplus.innerHTML = "Inara est une Stagalla, une femme de pierre possédant le pouvoir de contrôler la terre et la roche. Pacifique, elle ne prit pas les armes par conviction mais se retrouva très rapidement forcée de combattre comme le firent ses ancêtres qui avaient repoussé en leur temps le Premier Fléau gobelin lorsqu'elle vit son compagnon Terminus mourir sous les tirs de la Machine de Guerre. Traumatisée par les horreurs commises par le Magistrat ce jour-là, elle se rangea finalement du côté des Paladins, comme le souhaitait celui qu'elle aimait.";
            audio.src = "voiceline/Inara.ogg";
            video.src = "https://www.youtube.com/embed/qaeFn-ls7YU";
            montrevideo();
            break;
        case "Io": LeTitre.innerHTML = "Io";
            LeReste.innerHTML = "La Déesse Brisée";
            Limage.src = "banniere_perso/io.png";
            LaClasse.innerHTML = healer + "<br><i>(2200 PV)</i>";
            LogoClasse.src = "img/healer.png";
            descplus.innerHTML = "La déesse de la Lune, Io, a veillé durant des millénaires sur le monde des mortels jusqu'au jour où les Abysses occultèrent sa lumière de leurs ténèbres et brisèrent la Lune. À la suite de ce désastre, des morceaux de l'astre s'écrasèrent dans le Désert Brisé et, bien que protégés par les disciples de la déesse, attirèrent la convoitise du Magistère Karne qui souhaitait les utiliser dans sa guerre contre les Paladins. Ne sachant que faire, elle fut finalement convaincue par Jenos de descendre sur Terre pour dévoiler sa véritable apparence aux mortels et mettre sa puissance au service de la justice.";
            audio.src = "voiceline/Io.ogg";
            video.src = "https://www.youtube.com/embed/6hcOiyF3jLw";
            montrevideo();
            break;
        case "Jenos": LeTitre.innerHTML = "Jenos";
            LeReste.innerHTML = "La Force Astrale";
            Limage.src = "banniere_perso/jenos.png";
            LaClasse.innerHTML = healer + "<br><i>(2200 PV)</i>";
            LogoClasse.src = "img/healer.png";
            descplus.innerHTML = "Ayant cherché la sagesse ultime après avoir fui le Second Fléau, Jenos, alors jeune moine, la trouva écrite dans les étoiles et quitta la Terre. Durant plusieurs années, ses fidèles attendirent son retour en fondant le Pic de l'Ascension et en perpétuant son héritage. Alors que la guerre avait éclatée, le moine, devenu un dieu, redescendit sur Terre et rencontra Buck, avec qui il partagea ses connaissances jusqu'au jour où Lian et Khan, inspirés par la puissance du dieu, tentèrent de le rallier de force à leur camp, chose que Jenos refusa sans attendre.";
            audio.src = "voiceline/Jenos.ogg";
            video.src = "https://www.youtube.com/embed/bKwADF3VeHg";
            montrevideo();
            break;
        case "Khan": LeTitre.innerHTML = "Khan";
            LeReste.innerHTML = "Général Des Aico";
            Limage.src = "banniere_perso/khan.png";
            LaClasse.innerHTML = tank + "<br><i>(4000 PV)</i>";
            LogoClasse.src = "img/tank.png";
            descplus.innerHTML = "Véritable colosse et excellent soldat, Khan devint le conseiller, protecteur et amant de Lian grâce à sa force mais surtout grâce à sa loyauté envers la famille Aico, dont il dirige l'armée d'une main de fer. Froid, brutal et calculateur, il accepta de servir dans l'armée du Magistrat en lançant lui-même l'assaut sur le Pic de l'Ascension et en affrontant Jenos dans le but de le faire rallier son camp.";
            audio.src = "voiceline/Khan.ogg";
            video.src = "https://www.youtube.com/embed/36dGXD3v_8s";
            montrevideo();
            break;
        case "Kinessa": LeTitre.innerHTML = "Kinessa";
            LeReste.innerHTML = "La Chasseuse De Prime";
            Limage.src = "banniere_perso/kinessa.png";
            LaClasse.innerHTML = dmg + "<br><i>(2100 PV)</i>";
            LogoClasse.src = "img/dmg.png";
            descplus.innerHTML = "Kinessa est une chasseuse de primes reconnue dans tout le Royaume pour son application et sa dextérité. Elle doit en partie sa renommée à son ancien instructeur Strix, sniper et assassin pour le compte du Magistère Karne, qui lui apprit l'art du tir et lui offrit sa fameuse carabine sniper à énergie. En plus de pouvoir compter sur son entraînement militaire et sa carabine, Kinessa peut également bénéficier de mines de suppression pouvant détecter et infliger des dégâts aux ennemis et d'un télé-transporteur.";
            audio.src = "voiceline/Kinessa.ogg";
            video.src = "https://www.youtube.com/embed/xPcY4EginXE";
            montrevideo();
            break;
        case "Koga": LeTitre.innerHTML = "Koga";
            LeReste.innerHTML = "Le Dissident";
            Limage.src = "banniere_perso/koga.png";
            LaClasse.innerHTML = flank + "<br><i>(2000 PV)</i>";
            LogoClasse.src = "img/flank.png";
            descplus.innerHTML = "Ancien meilleur ninja de la guilde des Millemains, Koga fut cependant trahi par celle-ci de jalousie et dû s'enfuir. Le cœur empli de haine, il se mit à traquer et assassiner les membres de son ancienne famille un par un avant d'être repéré par les Paladins qui, en échange de son aide, l'aideront à trouver une vraie famille qui le fera ranger définitivement ses griffes. Et bien entendu, Koga a accepté de s'unir aux Paladins dans l'unique but de terminer ce qu'il a commencé.";
            audio.src = "voiceline/Koga.ogg";
            video.src = "https://www.youtube.com/embed/zyPkAiiyehs";
            montrevideo();
            break;
        case "Lex": LeTitre.innerHTML = "Lex";
            LeReste.innerHTML = "La Main De La Justice";
            Limage.src = "banniere_perso/lex.png";
            LaClasse.innerHTML = flank + "<br><i>(2200 PV)</i>";
            LogoClasse.src = "img/flank.png";
            descplus.innerHTML = "Juge impitoyable et dévoué du Tribunal Extérieur comme l'était son ami Androxus, Lex s'est mis en tête de traquer et vider, s'il le faut, ses magnums sur son vieil ami, quitte à ce que cela devienne une obsession. Bien que fidèle à la loi et aux consignes dictées par le Magistère Karne, Lex noue une forme de culpabilité et de haine vis-à-vis de son ami et de lui-même, se demandant régulièrement s'il ne vaut pas mieux capturer Androxus mort ou vif.";
            audio.src = "voiceline/Lex.ogg";
            video.src = "https://www.youtube.com/embed/PoTQvRptr6U";
            montrevideo();
            break;
        case "Lian": LeTitre.innerHTML = "Lian";
            LeReste.innerHTML = "Descandante Des Aico";
            Limage.src = "banniere_perso/lian.png";
            LaClasse.innerHTML = dmg + "<br><i>(2000 PV)</i>";
            LogoClasse.src = "img/dmg.png";
            descplus.innerHTML = "Héritière et actuelle dirigeante du trône de Rubis, Lian est avant tout une reine de la manipulation et du maniement du fusil. Son habileté est telle qu'elle peut toucher n'importe quel adversaire (y compris dans son dos) ou même en toucher plusieurs à la fois. Lorsque la guerre entre les Paladins et le Magistrat éclata, elle fut honorée d'être sollicitée par ce dernier et n'hésita pas une seconde à mettre à contribution toutes ses ressources humaines et matérielles dans toutes les batailles, particulièrement dans la bataille du Pic de l'Ascension qu'elle dirigea en personne dans le but de convaincre Jenos de rallier son camp.";
            audio.src = "voiceline/Lian.ogg";
            video.src = "https://www.youtube.com/embed/HOVa7gwUPJI";
            montrevideo();
            break;
        case "Maeve": LeTitre.innerHTML = "Maeve";
            LeReste.innerHTML = "La Fine Lame";
            Limage.src = "banniere_perso/maeve.png";
            LaClasse.innerHTML = flank + "<br><i>(1900 PV)</i>";
            LogoClasse.src = "img/flank.png";
            descplus.innerHTML = "Maeve est une jeune vagabonde et cambrioleuse possédant une particularité : son sang est à moitié tigron, ce qui lui confère des capacités surhumaines telles que la vitesse, l'agilité, la discrétion et la vision nocturne. En plus de ces capacités physiques exceptionnelles, Maeve possède également un talent inégalé dans le maniement du couteau qu'elle n'hésite jamais à dévoiler à ses employeurs.";
            audio.src = "voiceline/Maeve.ogg";
            video.src = "https://www.youtube.com/embed/WFhQNUkRBbU";
            montrevideo();
            break;
        case "Makoa": LeTitre.innerHTML = "Makoa";
            LeReste.innerHTML = "L'Ancien";
            Limage.src = "banniere_perso/makoa.png";
            LaClasse.innerHTML = tank + "<br><i>(4500 PV)</i>";
            LogoClasse.src = "img/tank.png";
            descplus.innerHTML = "Makoa l'Ancien est littéralement une force de la nature : indomptable protecteur de l’Île Grenouille servant de foyer aux derniers Ska'drins, il fut cependant contraint de quitter temporairement son île pour aider les Paladins et faire entendre la voix de la nature qu'il a juré de protéger. Pour l'heure, s'il souhaite que Valera tienne sa promesse, il va devoir démontrer sa dextérité au canon et à l'ancre et relâcher la furie de l'océan.";
            audio.src = "voiceline/Makoa.ogg";
            video.src = "https://www.youtube.com/embed/MHpDaR-XHp4";
            montrevideo();
            break;
        case "MalDamba": LeTitre.innerHTML = "Mal'Damba";
            LeReste.innerHTML = "L'Élu De Wekono";
            Limage.src = "banniere_perso/maldamba.png";
            LaClasse.innerHTML = healer + "<br><i>(2200 PV)</i>";
            LogoClasse.src = "img/healer.png";
            descplus.innerHTML = "Mal'Damba, le sorcier des îles, est également connu pour être le champion de Wekono, la déesse du chagrin et de la vengeance. Craint et respecté pour son expertise en poisons et magie noire, il est désormais redouté dans tout le royaume de par ses nouveaux pouvoirs et sa capacité à détruire quiconque refuse de se soumettre à la volonté de Wekono.";
            audio.src = "voiceline/MalDamba.ogg";
            video.src = "https://www.youtube.com/embed/lIUCISHw3iU";
            montrevideo();
            break;
        case "Moji": LeTitre.innerHTML = "Moji";
            LeReste.innerHTML = "Et Compagnie";
            Limage.src = "banniere_perso/moji.png";
            LaClasse.innerHTML = flank + "<br><i>(2200 PV)</i>";
            LogoClasse.src = "img/flank.png";
            descplus.innerHTML = "Magicienne issue de la race des Leiporis, Moji refusa de prendre la fuite lorsque la guerre entre Valera et Karne éclata. Consciente des risques et des ravages sur la nature, Moji invoqua l'étrange mais non moins destructeur esprit Po-Li, en fit son familier et accepta de se joindre aux Paladins pour pouvoir mettre un terme au conflit et aider son peuple à panser ses plaies.";
            audio.src = "voiceline/Moji.ogg";
            video.src = "https://www.youtube.com/embed/YlEGnKhrY4k";
            montrevideo();
            break;
        case "Octavia": LeTitre.innerHTML = "Octavia";
            LeReste.innerHTML = "L'Indomptable";
            Limage.src = "banniere_perso/octavia.png";
            LaClasse.innerHTML = dmg + "<br><i>(2200 PV)</i>";
            LogoClasse.src = "img/dmg.png";
            descplus.innerHTML = "Le conflit est ancien, la guerre est une perspective, mais la survie est le seul véritable objectif. Pour ceux qui survivent, il y a une vie meilleure quelque part après ce conflit; c'est pour cela qu'Octavia se bat: une vie meilleure pour nous tous.<br><br>Le creuset de la guerre a aiguisé ses instincts de champ de bataille au fil du rasoir. Mais ce qui distingue vraiment Octavia, c'est sa détermination sans faille et sa confiance en ses soldats. S'il y a de l'espoir, elle trouvera cette étincelle et la propulsera dans un feu rugissant, inspirant ses troupes avec une loyauté inébranlable. Les plus grandes menaces pour le Royaume devront survivre à la rencontre d'Octavia, l'Indomptable.";
            audio.src = "voiceline/Octavia.ogg";
            video.src = "https://www.youtube.com/embed/IyQZQf7Uq2s";
            montrevideo();
            break;
        case "Pip": LeTitre.innerHTML = "Pip";
            LeReste.innerHTML = "Le Petit Alchimiste";
            Limage.src = "banniere_perso/pip.png";
            LaClasse.innerHTML = healer + "<br><i>(2200 PV)</i>";
            LogoClasse.src = "img/healer.png";
            descplus.innerHTML = "Jeune vulpin spécialisé dans la pyrotechnie, Pip a choisi de quitter ses mangroves natales afin de découvrir le Royaume. Cependant, il ne trouva qu'un pays en pleine guerre civile et passe depuis la plupart de son temps à créer des potions incendiaires qu'il utilise contre l'armée du Magistrat et des potions de soins qu'il procure à ses alliés. Bien qu'apprécié pour son talent et son expertise, Pip n'en reste pas moins un renard au caractère rusé et imprévisible, le rendant potentiellement dangereux aux yeux de ses compagnons.";
            audio.src = "voiceline/Pip.ogg";
            video.src = "https://www.youtube.com/embed/N_ld-elEibM";
            montrevideo();
            break;
        case "Raum": LeTitre.innerHTML = "Raum";
            LeReste.innerHTML = "Rage Des Abysses";
            Limage.src = "banniere_perso/raum.png";
            LaClasse.innerHTML = tank + "<br><i>(4500 PV)</i>";
            LogoClasse.src = "img/tank.png";
            descplus.innerHTML = "Démon incarnant la rage, Raum est animé par un seul désir : l'annihilation totale de toute forme de vie. Ayant cependant vaincu tous ses opposants au sein des Abysses et étant gagné par l'ennui, il fut alors invoqué par un humain manipulé mentalement par Seris dans le Royaume, lui donnant accès à une quantité astronomique d'âmes encore intactes, du moins pour l'instant...";
            audio.src = "voiceline/Raum.ogg";
            video.src = "https://www.youtube.com/embed/_fY4IMKJH9s";
            montrevideo();
            break;
        case "Rei": LeTitre.innerHTML = "Rei";
            LeReste.innerHTML = "Erudite des Aico";
            Limage.src = "banniere_perso/rei.png";
            LaClasse.innerHTML = healer + "<br><i>(2200 PV)</i>";
            LogoClasse.src = "img/healer.png";
            descplus.innerHTML = "Quand Rei laissa sa garenne dans The Burrows, elle pointa ses oreilles vers la poursuite d’une maîtrise de la magie au-delà de tout être vivant. Sa quête la conduit au siège du Trône de Rubis, où elle trouve les moyens de réaliser ses ambitions.<br><br>Elle devint rapidement alliée et plus vite amie avec le Scion de la maison Aico, Lian, ayant accès aux ressources d’une puissante maison noble en échange de ses services et de ses conseils. Elle s’efforce d’exploiter avec encore plus de contrôle et de puissance les forces arcanes chaotiques qui courent à travers le Royaume et le lient ensemble. Rare prodige magique, son histoire vient de commencer.<br><br>L’érudit de la maison Aico poursuit la perfection, et elle jettera le livre à quiconque se met en travers de son chemin.";
            audio.src = "voiceline/Rei.ogg";
            video.src = "https://www.youtube.com/embed/d_j0MOYYlco";
            montrevideo();
            break;
        case "Ruckus": LeTitre.innerHTML = "Ruckus";
            LeReste.innerHTML = "Le Pire Des Amis";
            Limage.src = "banniere_perso/ruckus.png";
            LaClasse.innerHTML = tank + "<br><i>(4000 PV)</i>";
            LogoClasse.src = "img/tank.png";
            descplus.innerHTML = "Petit gobelin travailleur, rusé et inventif, Ruckus découvrit au fond d'une mine d'or une pierre d'âme appartenant à un Stagalla tombé au combat face au Premier Fléau. Conscient du potentiel énergétique du joyau, il décida de l'implanter dans son exosquelette minier en pensant améliorer ses capacités mais la pierre donna également à sa machine une conscience qui n'appréciait guère le petit gobelin. Malgré tout, la machine intelligente baptisée Bolt, consciente qu'ils seraient plus forts ensemble, accepta une alliance de principe et accompagne depuis Ruckus dans tout le Royaume en quête de richesses et de reconnaissance.";
            audio.src = "voiceline/Ruckus.ogg";
            video.src = "https://www.youtube.com/embed/iramSJvzOTY";
            montrevideo();
            break;
        case "Saati": LeTitre.innerHTML = "Saati";
            LeReste.innerHTML = "L'As de la Gachette";
            Limage.src = "banniere_perso/saati.png";
            LaClasse.innerHTML = dmg + "<br><i>(2200 PV)</i>";
            LogoClasse.src = "img/dmg.png";
            descplus.innerHTML = "Aucune dépense n’est épargnée pour être le meilleur des meilleurs. Elle travaille peut-être pour de l’argent, mais elle fait travailler son argent pour elle - avec l’équipement le plus récent pour compléter ses compétences. Vous pouvez essayer de vous mettre à l’abri, mais pas même une couverture solide peut vous sauver de Saati, le Trickshot.<br><br>Pour vous, un lancer de pièce est un pari. Pour elle, c’est une opportunité. Si vous entendez dire qu’elle veut votre prime, vous pourriez aussi bien arrêter de courir et rencontrer son face à face - de toute façon, cela ne fait que la retarder la nuit prochaine. Les plus grosses marques sont encore dans le Royaume, et ces grosses primes financeront BEAUCOUP de manège.";
            audio.src = "voiceline/Saati.ogg";
            video.src = "https://www.youtube.com/embed/0SN-Z56fpS4";
            montrevideo();
            break;
        case "Seris": LeTitre.innerHTML = "Seris";
            LeReste.innerHTML = "L'Oracle Des Abysses";
            Limage.src = "banniere_perso/seris.png";
            LaClasse.innerHTML = healer + "<br><i>(2200 PV)</i>";
            LogoClasse.src = "img/healer.png";
            descplus.innerHTML = "Seris, l'oracle des Abysses, tire son nom de la ville qu'elle détruisit en prenant possession du corps de la sœur de Sarah, la jeune femme qui devint Furia. Elle est, grâce à ses dons de voyage spatio-temporel et de prescience, la créature la plus puissante de l'Univers et la cause de nombreux événements à l'issue souvent dramatiques telles que la malédiction d'Androxus ou la corruption de Viktor qui semblent diriger le Royaume vers une destinée inconnue mais néanmoins inéluctable.";
            audio.src = "voiceline/Seris.ogg";
            video.src = "https://www.youtube.com/embed/MnFfvyfweJo";
            montrevideo();
            break;
        case "Sha Lin": LeTitre.innerHTML = "Sha Lin";
            LeReste.innerHTML = "Le Prince Du Désert";
            Limage.src = "banniere_perso/shalin.png";
            LaClasse.innerHTML = dmg + "<br><i>(2000 PV)</i>";
            LogoClasse.src = "img/dmg.png";
            descplus.innerHTML = "Aventurier et bourreau des cœurs légendaire, Sha Lin est un jeune archer venant d'une région désertique où vent et sable se côtoient sans cesse, ce qui lui permit naturellement de développer des techniques de camouflage et de doter son arc d'un enchantement rendant ses flèches aussi rapides, légères et puissantes que le désert lui-même. Malgré son exploit d'avoir trahi Zhin et la guilde des Millemains, Sha Lin ne s'arrêta pas là puisqu'il s'autoproclama défenseur du peuple durant le conflit qui opposa les Paladins au Magistrat. Plus tard, celui-ci aida Koga à s'enfuir de la guilde des Millemains et le convainquit de rejoindre les Paladins.";
            audio.src = "voiceline/ShaLin.ogg";
            video.src = "https://www.youtube.com/embed/w6W70UI0vNI";
            montrevideo();
            break;
        case "Skye": LeTitre.innerHTML = "Skye";
            LeReste.innerHTML = "L'Assassin Du Crépuscule";
            Limage.src = "banniere_perso/skye.png";
            LaClasse.innerHTML = flank + "<br><i>(2000 PV)</i>";
            LogoClasse.src = "img/flank.png";
            descplus.innerHTML = "Bien que née dans un milieu aisé, Skye renia sa famille pour devenir riche par ses propres moyens. A force de fréquenter la rue, elle commença une carrière de criminelle puis d'assassin contractuel d'abord au sein de la guilde des Millemains, où elle se mit au service de Zhin, puis au service du grand Magistère en personne. Armée d'une simple arbalète de poignet et d'une multitude de carreaux classiques et empoisonnés, Skye entend bien remplir son contrat en exterminant les Paladins.";
            audio.src = "voiceline/Skye.ogg";
            video.src = "https://www.youtube.com/embed/a8zkWCiKcbM";
            montrevideo();
            break;
        case "Strix": LeTitre.innerHTML = "Strix";
            LeReste.innerHTML = "La Plume Spectrale";
            Limage.src = "banniere_perso/strix.png";
            LaClasse.innerHTML = dmg + "<br><i>(2000 PV)</i>";
            LogoClasse.src = "img/dmg.png";
            descplus.innerHTML = "Instructeur, tireur d'élite et assassin à la solde du Magistrat, Strix est communément reconnu comme étant le meilleur sniper des Sentinelles, si ce n'est du Royaume. Sa réputation, qui n'est plus à faire, se base sur la dextérité, le camouflage et le sang-froid du tueur, implacable et impassible en toutes circonstances.";
            audio.src = "voiceline/Strix.ogg";
            video.src = "https://www.youtube.com/embed/tLuCtCDeHQo";
            montrevideo();
            break;
        case "Talus": LeTitre.innerHTML = "Talus";
            LeReste.innerHTML = "L'Enfant Des Ska'Drin";
            Limage.src = "banniere_perso/talus.png";
            LaClasse.innerHTML = flank + "<br><i>(1900 PV)</i>";
            LogoClasse.src = "img/flank.png";
            descplus.innerHTML = "Talus est un Ska'drin, une espèce ressemblant à un faune mais démontrant des capacités exceptionnelles en magie, et plus particulièrement en magie runique. Après avoir quitté l’Île Grenouille où son peuple s'était réfugié pour échapper au génocide, Talus, armé de son vérachargeur, de sa magie et de son incroyable naïveté, rejoignit les Paladins pour prouver à tous que les Ska'drins ont leur place légitime dans le Royaume.";
            audio.src = "voiceline/Talus.ogg";
            video.src = "https://www.youtube.com/embed/fZb3cQfx9Jk";
            montrevideo();
            break;
        case "Terminus": LeTitre.innerHTML = "Terminus";
            LeReste.innerHTML = "Le Déchu";
            Limage.src = "banniere_perso/terminus.png";
            LaClasse.innerHTML = tank + "<br><i>(4000 PV)</i>";
            LogoClasse.src = "img/tank.png";
            descplus.innerHTML = "Terminus est, tout comme Inara, un Stagalla, un géant de pierre à la force inébranlable. Cependant, lors de la création de la Résistance dans la forteresse de Soufflecroix, l'armée du Magistrat prit le château d'assaut et Terminus, convaincu que l'affrontement était inévitable, décida de prendre part au combat mais fut rapidement abattu d'un coup de canon dans la poitrine, sous les yeux horrifiés de ses camarades. Après cette violente et sanglante bataille, le cadavre du géant fut récupéré par le Magistrat qui le ressuscita grâce à des cristaux instables et le contrôla par sorcellerie. Sous cet état de mort-vivant, il sert d'arme vivante dépourvue d'émotions dans l'armée du Magistrat, détruisant tout sur son passage à grands coups de hache.";
            audio.src = "voiceline/Terminus.ogg";
            video.src = "https://www.youtube.com/embed/yMkWdg5Wph4";
            montrevideo();
            break;
        case "Tiberius": LeTitre.innerHTML = "Tiberius";
            LeReste.innerHTML = "Le Maître D'Armes";
            Limage.src = "banniere_perso/tiberius.png";
            LaClasse.innerHTML = dmg + "<br><i>(2200 PV)</i>";
            LogoClasse.src = "img/dmg.png";
            descplus.innerHTML = "Tigron légendaire, maître d'armes et éternel séducteur au tempérament à la fois insolent et impitoyable, Tiberius est devenu un véritable mythe au sein du Royaume de part ses talents de combattant et sa soif insatiable de combat. Cherchant perpétuellement un adversaire à sa hauteur, Tiberius s'entraîne sans relâche pour maîtriser ses chakrams ancestraux, ses pouvoirs magiques et la puissance de la Lame Légendaire, artefact ayant le pouvoir de bannir les créatures les plus immondes qui cependant, n'eût aucun effet sur Raum, ce qui entraîna Tiberius dans la guerre entre les Paladins et le Magistrat, dont seules les Abysses ressortiraient vainqueur.";
            audio.src = "voiceline/Tiberius.ogg";
            video.src = "https://www.youtube.com/embed/ZIv4moDpva0";
            montrevideo();
            break;
        case "Torvald": LeTitre.innerHTML = "Torvald";
            LeReste.innerHTML = "Le Sage Runique";
            Limage.src = "banniere_perso/torvald.png";
            LaClasse.innerHTML = tank + "<br><i>(3000 PV)</i>";
            LogoClasse.src = "img/tank.png";
            descplus.innerHTML = "Inventeur de génie et chercheur suprême au sein d'Engrenage, Torvald est un passionné d'Histoire, de runes et de magie. Pacifiste de nature, il fut pourtant contraint de prendre part à la guerre contre les Paladins s'il souhaitait poursuivre ses recherches. Depuis lors, il n'attend qu'une chose : que la guerre prenne fin pour pouvoir se remettre au travail.";
            audio.src = "voiceline/Torvald.ogg";
            video.src = "https://www.youtube.com/embed/s0GIfY3RdAU";
            montrevideo();
            break;
        case "Tyra": LeTitre.innerHTML = "Tyra";
            LeReste.innerHTML = "L'Indomptée";
            Limage.src = "banniere_perso/tyra.png";
            LaClasse.innerHTML = dmg + "<br><i>(2400 PV)</i>";
            LogoClasse.src = "img/dmg.png";
            descplus.innerHTML = "yra est une ancienne Sentinelle venant du nord du Royaume. Après l'échec de la dernière mission des Sentinelles, elle décida de quitter la capitale pour chasser les monstres qui terrorisaient sa terre natale avant de trouver un nouveau but : mettre à profit son talent au fusil, ses grenades et ses bombes incendiaires pour épauler les Paladins.";
            audio.src = "voiceline/Tyra.ogg";
            video.src = "https://www.youtube.com/embed/V5TSsepFwBM";
            montrevideo();
            break;
        case "Vatu": LeTitre.innerHTML = "Vatu";
            LeReste.innerHTML = "L'Ombre";
            Limage.src = "banniere_perso/vatu.png";
            LaClasse.innerHTML = flank + "<br><i>(1900 PV)</i>";
            LogoClasse.src = "img/flank.png";
            descplus.innerHTML = "Derrière chaque porte de l’esprit se trouve la peur de l’obscurité dans le coin d’une pièce faiblement éclairée. C’est l’inconnu — la terreur sans forme, mais avec un nom : l’Ombre.<br><br>Les origines de Vatu sont enveloppées dans la même ombre qu’il utilise comme arme. Il est le couteau dans la nuit, mettant fin à un conflit éternel – il est la mort prématurée, jamais confirmée comme accidentelle. Lui et la guilde des Mille-Mains ont une entente : ils lui fournissent du travail et de l’argent, et il s’occupe de leurs problèmes. La seule chose qui ressort clairement de ses actions, c’est son désir de protéger son peuple Ska’Drin et sa capacité meurtrière de le faire.<br><br>Brandissant un Kunai aiguisé et mystérieuse magie d’ombre, Vatu prend soin des affaires avec une efficacité impitoyable égalée seulement par son code strict d’éthique. Ses yeux ne sont pas ceux que vous voulez voir en vous regardant de l’obscurité, car il est déjà trop tard.";
            audio.src = "voiceline/Vatu.ogg";
            video.src = "https://www.youtube.com/embed/iW7E6BHSr1Q";
            montrevideo();
            break;
        case "Viktor": LeTitre.innerHTML = "Viktor";
            LeReste.innerHTML = "Le Loup Solitaire";
            Limage.src = "banniere_perso/viktor.png";
            LaClasse.innerHTML = dmg + "<br><i>(2200 PV)</i>";
            LogoClasse.src = "img/dmg.png";
            descplus.innerHTML = "Ancien commandant des Sentinelles, Viktor était incontestablement le meilleur soldat du Royaume. Rétrogradé et dépouillé de sa gloire par le magistrat à la suite de l'échec de sa dernière mission, Viktor n'en est pas moins resté fidèle à celui-ci et, armé d'un simple fusil d'assaut, de grenades et de son talent au combat, a sans cesse repoussé ses limites dans la lutte contre les Paladins. À la suite d'un rude affrontement, il succomba à ses blessures avant d'être ressuscité et renforcé par Seris, l'oracle des Abysses. ";
            audio.src = "voiceline/Viktor.ogg";
            video.src = "https://www.youtube.com/embed/ezNQIj0MhQQ";
            montrevideo();
            break;
        case "Vivian": LeTitre.innerHTML = "Vivian";
            LeReste.innerHTML = "La Fourbe";
            Limage.src = "banniere_perso/vivian.png";
            LaClasse.innerHTML = dmg + "<br><i>(2200 PV)</i>";
            LogoClasse.src = "img/dmg.png";
            descplus.innerHTML = "Cette femme aussi énigmatique que charismatique dirige le centre de recherches militaire de la capitale. Peu scrupuleuse et manipulatrice, elle fut la première à convaincre sa hiérarchie du potentiel militaire des armes alimentées au cristal dans le seul but d'utiliser son pistolet-mitrailleur et ses drones au summum de leurs capacités afin d'éliminer quiconque se dresserait sur son chemin vers le pouvoir.";
            audio.src = "voiceline/Vivian.ogg";
            video.src = "https://www.youtube.com/embed/_oEgljEEkAU";
            montrevideo();
            break;
        case "Vora": LeTitre.innerHTML = "Vora";
            LeReste.innerHTML = "L'Oracle";
            Limage.src = "banniere_perso/vora.png";
            LaClasse.innerHTML = flank + "<br><i>(2000 PV)</i>";
            LogoClasse.src = "img/flank.png";
            descplus.innerHTML = "Une vie, autrefois consacrée à Io, la déesse de la lune. Son ordre martial sacré était chargé de protéger les anciens sceaux, mais même eux ne connaissaient pas l'étendue du chaos en dessous. Se sentant abandonnée par sa déesse, entourée de prières sans réponse et de corps brisés, elle a choisi d'embrasser ce chaos . Le Royaume est sur la voie de l'autodestruction, mais elle le délivrera de ce destin. Elle apporte la fin ... de ces guerres, de cette souffrance - la fin de tout. Ceux qui la connaissent redoutent sa venue, car elle est Vora, le messager de la fin du royaume ; et ils ne sont pas préparés.";
            audio.src = "voiceline/Vora.ogg";
            video.src = "https://www.youtube.com/embed/hStoaHFq8cs";
            montrevideo();
            break;
        case "Willo": LeTitre.innerHTML = "Willo";
            LeReste.innerHTML = "La Fée De La Cour Estivale";
            Limage.src = "banniere_perso/willo.png";
            LaClasse.innerHTML = dmg + "<br><i>(2200 PV)</i>";
            LogoClasse.src = "img/dmg.png";
            descplus.innerHTML = "Petite fée gardienne de la nature, Willo éprouve une haine et une agressivité extrêmes envers le Royaume, surtout depuis qu'il est pris dans la guerre entre les Paladins et le Magistrat. Bien que très jeune, la petite fée semble posséder des pouvoirs très puissants en lien avec la nature, que ce soit dans l'utilisation de spores toxiques pour empoisonner la cible ou dans l'utilisation de graines explosives très puissantes.";
            audio.src = "voiceline/Willo.ogg";
            video.src = "https://www.youtube.com/embed/KC5iq-OZZZs";
            montrevideo();
            break;
        case "Yagorath": LeTitre.innerHTML = "Yagorath";
            LeReste.innerHTML = "L'insatiable";
            Limage.src = "banniere_perso/yagorath.png";
            LaClasse.innerHTML = tank + "<br><i>(6000 PV)</i>";
            LogoClasse.src = "img/tank.png";
            descplus.innerHTML = "Vos joies et vos espérances. Vos craintes et vos doutes. Tous vos petits conflits. Totalement dépourvu de sens. Elle est Yagorath, le Dévoreur. Elle est ce que c'est à consommer - absolument. Tout ce qui n'est pas déjà elle est assimilé, répandant son être à travers l'univers dans une faim sans fin. Momentanément affaiblie par les actions futiles d'une déesse brisée, elle émerge maintenant pour mettre fin à ce qui a commencé - la seule fin qui pourrait être.";
            audio.src = "voiceline/Yagorath.ogg";
            video.src = "https://www.youtube.com/embed/Gj4Oc_qZzd4";
            montrevideo();
            break;
        case "Ying": LeTitre.innerHTML = "Ying";
            LeReste.innerHTML = "L'Épanouis";
            Limage.src = "banniere_perso/ying.png";
            LaClasse.innerHTML = healer + "<br><i>(2200 PV)</i>";
            LogoClasse.src = "img/healer.png";
            descplus.innerHTML = "Illusionniste de talent, Ying est une jeune et belle aventurière possédant de nombreuses capacités utiles en combat comme le clonage ou le soin. Animée par un désir de justice et ayant un cœur pur, elle prit la décision de lutter contre la tyrannie du Magistrat quand celui-ci décréta la restriction de la magie en se joignant aux Paladins.Elle est spécialiste de la magie et peut avoir un effet dévastateur sur ses ennemis mais au contraire un effet positif pour ses alliés la magie à plusieurs forme faite attention.";
            audio.src = "voiceline/Ying.ogg";
            video.src = "https://www.youtube.com/embed/HBgQNIgjFyw";
            montrevideo();
            break;
        case "Zhin": LeTitre.innerHTML = "Zhin";
            LeReste.innerHTML = "Le Tyran";
            Limage.src = "banniere_perso/zhin.png";
            LaClasse.innerHTML = flank + "<br><i>(2000 PV)</i>";
            LogoClasse.src = "img/flank.png";
            descplus.innerHTML = "Maître incontesté de la guilde des Millemains depuis l'âge de 20 ans, Zhin est un seigneur de guerre et baron du crime déterminé, tyrannique et cruel. Cependant, le tyran n'hésita pas à prendre le jeune Koga en pitié et à le recueillir comme son fils avant d'en faire le meilleur ninja de la guilde puis de chercher à l'éliminer à cause d'une sombre histoire. Depuis le début du conflit opposant le Magistrat aux Paladins, Zhin se pose en observateur et ne dégainera son épée de feu que lorsque son apprenti viendra pour sa dernière leçon.";
            audio.src = "voiceline/Zhin.ogg";
            video.src = "https://www.youtube.com/embed/s4fdxUd8U9U";
            montrevideo();
            break;
        case "pisapou":
        case "Pisapou":
            Lerreur.innerHTML = "Le meilleur joueur du jeu ?";
            errouge()
            break;
        case "ravier":
        case "Ravier":
            Lerreur.innerHTML = "C'est vous ?";
            errouge()
            break;
        case "vladislas":
        case "Vladislas":
            Lerreur.innerHTML = "Le plus talentueux des élèves !";
            errouge()
            break;
        case "overwatch":
        case "Overwatch":
        case "OverWatch":
            Lerreur.innerHTML = "Pas top comme jeu ...";
            errouge()
            break;
        case "berthelot":
        case "Berthelot":
            Lerreur.innerHTML = "Le meilleur lycée au monde !";
            errouge()
            break;
        case "nsi":
        case "NSI":
            Lerreur.innerHTML = "La meilleur matière au monde !";
            errouge()
            break;
        default:
            Lerreur.innerHTML = "Aucun Champion Trouvé ...";
            errouge()
    }
}
